export const data = JSON.parse("{\"key\":\"v-9d59cba4\",\"path\":\"/code/2018-09-13-Rotate-Array-cn.html\",\"title\":\"旋转数组\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"旋转数组\",\"description\":\"给定一个数组，将数组中的元素向右移动 k 个位置，其中 k 是非负数。\",\"tag\":[\"leetcode\",\"array\",\"Easy-Collection\"],\"date\":\"2018-09-13T00:00:00.000Z\",\"article\":false,\"category\":\"algorithms\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yinheng.me/code/2018-09-13-Rotate-Array-cn.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Best Intention\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"旋转数组\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"给定一个数组，将数组中的元素向右移动 k 个位置，其中 k 是非负数。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Maple Yin\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"leetcode\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"array\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Easy-Collection\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2018-09-13T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"旋转数组\\\",\\\"description\\\":\\\"给定一个数组，将数组中的元素向右移动 k 个位置，其中 k 是非负数。\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":2.22,\"words\":665},\"filePathRelative\":\"code/2018-09-13-Rotate-Array-cn.md\",\"localizedDate\":\"2018年9月13日\",\"excerpt\":\"<blockquote>\\n<p>给定一个数组，将数组中的元素向右移动 <em>k</em> 个位置，其中 <em>k</em> 是非负数。</p>\\n<p><strong>示例 1:</strong></p>\\n<div class=\\\"language-text line-numbers-mode\\\" data-ext=\\\"text\\\"><pre class=\\\"language-text\\\"><code>输入: [1,2,3,4,5,6,7] 和 k = 3\\n输出: [5,6,7,1,2,3,4]\\n解释:\\n向右旋转 1 步: [7,1,2,3,4,5,6]\\n向右旋转 2 步: [6,7,1,2,3,4,5]\\n向右旋转 3 步: [5,6,7,1,2,3,4]\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div><p><strong>示例 2:</strong></p>\\n<div class=\\\"language-text line-numbers-mode\\\" data-ext=\\\"text\\\"><pre class=\\\"language-text\\\"><code>输入: [-1,-100,3,99] 和 k = 2\\n输出: [3,99,-1,-100]\\n解释: \\n向右旋转 1 步: [99,-1,-100,3]\\n向右旋转 2 步: [3,99,-1,-100]\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div><p><strong>说明:</strong></p>\\n<ul>\\n<li>尽可能想出更多的解决方案，至少有三种不同的方法可以解决这个问题。</li>\\n<li>要求使用空间复杂度为 O(1) 的原地算法。</li>\\n</ul>\\n</blockquote>\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
