export const data = JSON.parse("{\"key\":\"v-b8066e70\",\"path\":\"/code/2019-06-11-Two-City-Scheduling.html\",\"title\":\"两地调度\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"两地调度\",\"description\":\"公司计划面试 2N 人。第 i 人飞往 A 市的费用为 costs[i][0]，飞往 B 市的费用为 costs[i][1]。\",\"tag\":[\"leetcode\",\"array\",\"Easy-Collection\"],\"date\":\"2019-06-11T00:00:00.000Z\",\"article\":false,\"category\":\"algorithms\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://yinheng.me/code/2019-06-11-Two-City-Scheduling.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Best Intention\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"两地调度\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"公司计划面试 2N 人。第 i 人飞往 A 市的费用为 costs[i][0]，飞往 B 市的费用为 costs[i][1]。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Maple Yin\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"leetcode\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"array\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Easy-Collection\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-06-11T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"两地调度\\\",\\\"description\\\":\\\"公司计划面试 2N 人。第 i 人飞往 A 市的费用为 costs[i][0]，飞往 B 市的费用为 costs[i][1]。\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":1.28,\"words\":383},\"filePathRelative\":\"code/2019-06-11-Two-City-Scheduling.md\",\"localizedDate\":\"2019年6月11日\",\"excerpt\":\"<blockquote>\\n<p>公司计划面试 <code>2N</code> 人。第 i 人飞往 A 市的费用为 <code>costs[i][0]</code>，飞往 B 市的费用为 <code>costs[i][1]</code>。</p>\\n<p>返回将每个人都飞到某座城市的最低费用，要求每个城市都有 N 人抵达。</p>\\n<p>示例：</p>\\n<div class=\\\"language-text line-numbers-mode\\\" data-ext=\\\"text\\\"><pre class=\\\"language-text\\\"><code>输入：[[10,20],[30,200],[400,50],[30,20]]\\n输出：110\\n解释：\\n第一个人去 A 市，费用为 10。\\n第二个人去 A 市，费用为 30。\\n第三个人去 B 市，费用为 50。\\n第四个人去 B 市，费用为 20。\\n\\n最低总费用为 10 + 30 + 50 + 20 = 110，每个城市都有一半的人在面试。\\n</code></pre><div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div><p>提示：</p>\\n<ol>\\n<li><code>1 &lt;= costs.length &lt;= 100</code></li>\\n<li><code>costs.length</code> 为偶数</li>\\n<li><code>1 &lt;= costs[i][0], costs[i][1] &lt;= 1000</code></li>\\n</ol>\\n</blockquote>\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
